name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run RestAssured BDD Tests and Generate Cucumber Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven Installation
        run: |
          mvn -version
          which mvn

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Run BDD Test Suite
        run: |
          chmod +x mvnw
          chmod +x runSuite.sh
          ./runSuite.sh

      - name: Generate Cucumber Report
        run: |
          chmod +x openReport.sh
          ./openReport.sh &
          sleep 10
          pkill -f cucumber

      - name: Upload Cucumber Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports

      - name: Display Cucumber Report Info
        run: echo "Cucumber Report is available in the CI/CD artifacts."
